Modified build script

diff --git a/buildConquer b/buildConquer
--- a/buildConquer
+++ b/buildConquer
@@ -7,6 +7,14 @@ else
 	echo Didn\'t find java, version 15
 	exit 1
 fi
+if ! command -v musescore3 &> /dev/null; then
+	echo "The command musescore3 could not be found"
+	exit 1
+fi
+if [ `gcc -dumpversion` != "10" ]; then
+	echo Didn\'t find gcc-10
+	exit 1
+fi
 export TARGET="all"
 unameOut="$(uname -s)"
 case "${unameOut}" in
@@ -135,7 +143,7 @@ if [[ -z "${IS_WIN}" ]]; then
 	echo Version: 0.0.1>>control
 	echo Section: games>>control
 	echo Architecture: `dpkg --print-architecture`>>control
-	echo Depends: libcurl4>>control
+	echo Depends: libcurl4, libarchive13>>control
 	echo Maintainer: JCWasmx86 >>control
 	echo Description: The strategy game conquer >>control
 	cd ../..
